library("sqldf")
getwd()
#data=read.csv("students.csv")
students = read.csv(file.choose(),header = TRUE)
sqldf("select min(marks) from students")
sqldf("select count(*) from students")
sqldf("select * from students where roll_no>3")
sqldf("select * from students where marks<24")
sqldf("select * from students where name='A'")
sqldf("select DISTINCT Name from students ")
min(students$marks)
max(students$marks)
sum(students$marks)
nrow(students)
ncol(students)
nrow(students[students$marks>24,])
nrow(students[students$marks>57,])
sqldf("select name,marks from students 
      where marks>33")
sqldf("select name from students where marks<64")

